### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by sukuasoft**
@ad3ldev  In this PR, add dark mode to the project. I made changes to the files.
1. index.html
2. src/index.js
3. src/style.scss

And one of the changes I made to existing codes was to reduce the size of the game buttons so that everything fits on the screen.

### CODE REVIEW

**Comment by sukuasoft** [comment]
@ad3ldev I don't see the comment

**Comment by ad3ldev** [comment]
It's about using let instead of var since it's the new standard of creating mutable variables in JavaScript

**Comment by sukuasoft** [comment]
Okay, I'm going to make this change right now

**Comment by sukuasoft** [comment]
@ad3ldev Updated

**Pull request merged**
